package ulb.view.common;

import javafx.scene.image.Image;
import ulb.configuration.Configuration;
import ulb.model.domain.Element;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Loads Bugemon sprite images from classpath resources with a three-tier fallback chain
 * and an in-memory path cache.
 *
 * <p>Fallback order in {@link #loadSpriteForBugemon}:
 * <ol>
 *   <li>The requested {@code spritePath} (front or back variant depending on {@code useBackSprite})</li>
 *   <li>An element-based generic sprite (e.g. the fire-type placeholder)</li>
 *   <li>The absolute default sprite bundled with the application</li>
 * </ol>
 *
 * <p><b>Caching invariant:</b> every call to {@link #loadResource} stores its result (including
 * {@code Optional.empty()}) in {@code imageCache}, so repeated loads of the same path are
 * cheap and safe. Create one {@code SpriteLoader} per long-lived component and reuse it;
 * do not create a new instance per frame or per Bugemon render call.
 */
public class SpriteLoader {

    private final Map<String, Optional<Image>> imageCache = new HashMap<>();

    /**
     * Loads the sprite for a Bugemon, applying the three-tier fallback chain when the
     * requested path is unavailable.
     *
     * <p>If {@code spritePath} is {@code null} or blank the method skips directly to the
     * element-based fallback and then to the default sprite, never returning {@code null}.
     *
     * @param spritePath    classpath path stored for this Bugemon; may be {@code null} or blank
     * @param element       element type used to pick an element-themed fallback sprite
     * @param isPlayer      {@code true} if this is the player's Bugemon — affects which default
     *                      sprite is chosen and which directory is preferred for back sprites
     * @param useBackSprite {@code true} to request the back-facing sprite (used during battle
     *                      for the player's side)
     * @return a non-{@code null} {@code Optional} that is empty only when no sprite at all
     *         could be located on the classpath
     */
    public Optional<Image> loadSpriteForBugemon(String spritePath, Element element, boolean isPlayer, boolean useBackSprite) {
        if (spritePath == null || spritePath.isBlank()) {
            Optional<Image> fallback = tryLoadSprite(fallbackByElement(element, isPlayer, useBackSprite));
            return fallback.isPresent() ? fallback : loadDefaultSprite(isPlayer);
        }

        Optional<Image> sprite = tryLoadSprite(spritePath, useBackSprite);
        if (sprite.isPresent()) return sprite;

        return tryLoadSprite(fallbackByElement(element, isPlayer, useBackSprite))
                .or(() -> loadDefaultSprite(isPlayer));
    }

    /** Attempts to load the front-facing sprite at {@code spritePath}. */
    public Optional<Image> tryLoadSprite(String spritePath) {
        return tryLoadSprite(spritePath, false);
    }

    /**
     * Attempts to load a sprite, choosing the front or back sprite directory based on
     * {@code useBackSprite}, and trying all path variants generated by
     * {@link SpritePath#defaultCandidates}.
     *
     * @param spritePath    raw classpath path; returns {@code empty} if {@code null} or blank
     * @param useBackSprite {@code true} to look in the back-sprites directory
     */
    public Optional<Image> tryLoadSprite(String spritePath, boolean useBackSprite) {
        Optional<SpritePath> parsed = SpritePath.from(spritePath);
        if (parsed.isEmpty()) return Optional.empty();

        String folder = useBackSprite
                ? Configuration.BUGEMONS_SPRITES_BACK_PATH
                : Configuration.BUGEMONS_SPRITES_PATH;

        List<String> candidates = new ArrayList<>();
        for (String candidate : parsed.get().defaultCandidates(folder)) {
            addCandidate(candidates, candidate);
        }

        for (String candidate : candidates) {
            Optional<Image> image = loadResource(candidate);
            if (image.isPresent()) return image;
        }

        return Optional.empty();
    }

    private Optional<Image> loadDefaultSprite(boolean isPlayer) {
        if (isPlayer) {
            Optional<Image> image = tryLoadSprite(Configuration.GRASS_NO_NAME_SPRITE_PATH);
            if (image.isPresent()) return image;

            image = tryLoadSprite(Configuration.FIRE_NO_NAME_SPRITE_PATH);
            if (image.isPresent()) return image;

            image = tryLoadSprite(Configuration.WATER_NO_NAME_SPRITE_PATH);
            if (image.isPresent()) return image;
        }

        return tryLoadSprite(Configuration.DEFAULT_BUGEMON_SPRITE_PATH);
    }

    private String fallbackByElement(Element element, boolean isPlayer, boolean useBackSprite) {
        String normalized = element == null ? "" : element.name().trim().toUpperCase();
        return switch (normalized) {
            case "FIRE"  -> Configuration.FIRE_NO_NAME_SPRITE_PATH;
            case "ICE"   -> Configuration.WATER_NO_NAME_SPRITE_PATH;
            case "PLANT" -> Configuration.GRASS_NO_NAME_SPRITE_PATH;
            default -> isPlayer
                    ? useBackSprite
                        ? Configuration.DEFAULT_BUGEMON_BACK_SPRITE_PATH
                        : Configuration.GRASS_NO_NAME_SPRITE_PATH
                    : Configuration.DEFAULT_BUGEMON_SPRITE_PATH;
        };
    }

    // Adds the candidate and its .png / .PNG case variants, deduplicating as it goes.
    // Needed because some filesystems (Windows, macOS default) are case-insensitive while
    // others (Linux) are not, and sprites ship with inconsistent extension casing.
    private void addCandidate(List<String> candidates, String candidate) {
        if (candidate == null || candidate.isBlank()) return;

        if (!candidates.contains(candidate)) candidates.add(candidate);

        String lowerPng = candidate.replaceFirst("(?i)\\.png$", ".png");
        if (!candidates.contains(lowerPng)) candidates.add(lowerPng);

        String upperPng = candidate.replaceFirst("(?i)\\.png$", ".PNG");
        if (!candidates.contains(upperPng)) candidates.add(upperPng);
    }

    private Optional<Image> loadResource(String resourcePath) {
        if (resourcePath == null || resourcePath.isBlank()) return Optional.empty();

        Optional<Image> cached = imageCache.get(resourcePath);
        if (cached != null) return cached;

        Optional<Image> loaded = Optional.empty();
        try (InputStream stream = getClass().getResourceAsStream(resourcePath)) {
            if (stream != null) loaded = Optional.of(new Image(stream));
        } catch (IOException e) {
            loaded = Optional.empty();
        }

        imageCache.put(resourcePath, loaded);
        return loaded;
    }
}
