CREATE TABLE IF NOT EXISTS attaque (
    id TEXT PRIMARY KEY,

    nom TEXT NOT NULL,
    type TEXT NOT NULL,
    description TEXT NOT NULL,
    puissance INT NOT NULL,
    precision FLOAT NOT NULL DEFAULT 1.0,
    priorite INT NOT NULL DEFAULT 0,
    est_magique BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE attaque ADD COLUMN IF NOT EXISTS precision FLOAT NOT NULL DEFAULT 1.0;
ALTER TABLE attaque ADD COLUMN IF NOT EXISTS priorite INT NOT NULL DEFAULT 0;
ALTER TABLE attaque ADD COLUMN IF NOT EXISTS est_magique BOOLEAN NOT NULL DEFAULT FALSE;
