ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS floor_reached INTEGER NOT NULL DEFAULT 0;
ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS combats_won INTEGER NOT NULL DEFAULT 0;
ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS bugemons_defeated INTEGER NOT NULL DEFAULT 0;
ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS bugemons_lost INTEGER NOT NULL DEFAULT 0;
ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS flawless_floors INTEGER NOT NULL DEFAULT 0;
