CREATE TABLE IF NOT EXISTS team (
    id   SERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    team_type VARCHAR(64) NOT NULL DEFAULT 'FREE_BATTLE',
    user_id INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE team ADD COLUMN IF NOT EXISTS team_type VARCHAR(64) NOT NULL DEFAULT 'FREE_BATTLE';
ALTER TABLE team ADD COLUMN IF NOT EXISTS user_id INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS team_name_type_user_unique ON team(name, team_type, user_id);

CREATE TABLE IF NOT EXISTS team_members (
    team_id    INTEGER NOT NULL,
    slot       INTEGER NOT NULL,
    bugemon_id VARCHAR(64) NOT NULL,
    niveau     INT NOT NULL DEFAULT 1,
    xp         BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (team_id, slot),
    FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE
);

ALTER TABLE team_members ADD COLUMN IF NOT EXISTS niveau INT NOT NULL DEFAULT 1;
ALTER TABLE team_members ADD COLUMN IF NOT EXISTS xp BIGINT NOT NULL DEFAULT 0;