package ulb.controller.battle.towerMode;

import ulb.controller.ApplicationController;
import ulb.exception.MissingLevelUpBugemonException;
import ulb.model.domain.BattleState;
import ulb.service.battle.BattleSystem;
import ulb.model.domain.Bugemon;
import ulb.model.domain.Statistics;
import ulb.service.levelup.LevelUpBonusService;
import ulb.view.battle.towerMode.LevelupDisplayData;
import ulb.view.battle.towerMode.LevelupView;
import ulb.model.domain.status.Bonus;

import java.util.List;

/**
 * Controller responsible for the level-up reward screen.
 *
 * It displays the 3 rewards options generated by {@code LevelUpBonusService}, shows a preview of the stat changes
 * when hovering over a choice and applies the reward to the bugemon before resuming the game
 */

public class NoLevelupController implements LevelupView.Listener {
    private final ApplicationController applicationController;
    private final LevelupView view;
    private Bugemon bugemon;
    private final BattleSystem battleSystem;
    private List<Bonus> bonusOptions;


    public NoLevelupController(LevelupView view, ApplicationController applicationController, BattleSystem battleSystem) {
        this.applicationController = applicationController;
        this.battleSystem = battleSystem;
        this.view = view;

        LevelUpBonusService bonusService = new LevelUpBonusService();
        LevelupDisplayBuilder previewBuilder = new LevelupDisplayBuilder();
        this.bugemon = battleSystem.getCurrentLevelUpBugemon();

        if (this.bugemon == null) {
            this.bugemon = battleSystem.getActiveBugemonOfPlayer();
        }

        if (this.bugemon == null) {
            throw new MissingLevelUpBugemonException("Cannot initialize level-up flow: no current or active player Bugemon found.");
        }

        bonusOptions = bonusService.generateBonuses();
        LevelupDisplayData displayData = previewBuilder.build(this.bugemon, this.bugemon.getLevel(), bonusOptions);
        view.displayLevelup(displayData);

        view.setListener(this);
    }

    /**
     * Updates the preview panel with the stat evolution of the selected bonus.
     */
    @Override
    public void onBonusSelected(int bonusIndex) {
        view.displayStatsEvolution(getOldStats(bugemon), bonusIndex);
        view.displayConfirmButton();
    }

    /**
     * Captures the Bugemon's current stats before the bonus is applied, to show a before/after comparison
     */
    @Override
    public void onBonusConfirmed(int bonusIndex) {
        if (bugemon != null) {
            bugemon.applyLevelUpBonus(bonusOptions.get(bonusIndex));
        }
        battleSystem.continueHandleBattleOutcome();
        if (battleSystem.getBattleState() != BattleState.END) {
            applicationController.showGameScreen();
        }
    }

    // retrieve a copy of the bugemon's stats to show the preview post bonus appliance
    private Bonus getOldStats(Bugemon bugemon) {
        return new Bonus (
                getStatsFromBugemon(bugemon).getMaxHp(),
                bugemon.getAttack(),
                bugemon.getDefense(),
                bugemon.getInitiative()
        );
    }

    private Statistics getStatsFromBugemon(Bugemon bugemon){
        return bugemon.getStats();
    }
}
